### ISSUE TITLE
[Request] Add application: Hypothesis

### ISSUE THREAD

**Issue by grvsmth** [lgessler/mala#4]
1. App name: Hypothesis
2. Release year: 2013
3. Icon (if available): https://d242fdlp0qlcia.cloudfront.net/uploads/2016/12/15180059/logo_new.png
4. Screenshot (if available): https://hyp.is/go?url=https%3A%2F%2Fwww.bartleby.com%2F101%2F549.html&group=__world__
5. Link to paper (if available): 
6. Link to code if open source, or webpage if not: https://github.com/hypothesis
7. Supported [data types](https://lgessler.com/mala/about.html): overlapping-spans
8. Supported [import formats](https://lgessler.com/mala/about.html): json
9. Supported [export formats](https://lgessler.com/mala/about.html): json
10. Availability (open-source, closed-source, or commercial): 
11. Short summary (no more than 180 characters):

**Comment by grvsmth** [comment]
10. Availability: open-source
11. Short summary (no more than 180 characters): A conversation layer over the entire web that works everywhere, without needing implementation by any underlying site.

**Comment by lgessler** [comment]
Thanks for the contribution! I adjusted the description a little bit, hope it looks okay.
