### ISSUE TITLE
[Request] Add application: Hexatomic

### ISSUE THREAD

**Issue by sdruskat** [lgessler/mala#5]
Hi @lgessler, hope you're well. Here's our annotation tool, finally released v1.0 :).

1. App name: Hexatomic
2. Release year: 2022
3. Icon (if available): 
4. Screenshot (if available): 
![image](https://user-images.githubusercontent.com/3007126/187392416-f694598b-0401-48c2-a3a2-950ee4f7e1d0.png)

5. Link to paper (if available): 
6. Link to code if open source, or webpage if not: https://github.com/hexatomic/hexatomic
7. Supported [data types](https://lgessler.com/mala/about.html): 
    - tags
    - chunk-spans
    - overlapping-spans
    - constituency-tree
    - dependency-tree
    - graph
9. Supported [import formats](https://lgessler.com/mala/about.html): 
    - plaintext
    - xml
11. Supported [export formats](https://lgessler.com/mala/about.html): 
    - xml
13. Availability (open-source, closed-source, or commercial): 
    - open-source (Apache-2.0)
15. Short summary (no more than 180 characters):

> Extensible multi-layer annotation (e.g., graph, grid) desktop tool with ANNIS support and high format compatibility, for Linux, Win, MacOS. Supports arbitrary annotation types.

**Comment by sdruskat** [comment]
Pinging @thomaskrause :point_up:

**Comment by lgessler** [comment]
Hi @sdruskat, nice to hear from you! 😀

I've added Hexatomic in 936cf2e8a916f4c1ffc1f1c777d7469bee6bb0b0, see live at https://lgessler.com/mala/hexatomic. Please let me know if you'd like anything changed.

Congrats on 1.0 by the way, I'm eager to try Hexatomic out.

**Comment by sdruskat** [comment]
Thanks @lgessler, looks great!

Yea, test it and let us know what you think :).
